version: '3'
services:
  database:
    image: postgres
    container_name: postgres_docker
    restart: unless-stopped
    ports:
      - 5643:5432
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
