version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgreslatest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 6432:5432 
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
