version: '3'
 
services:
  mysql:
    image: mysql:5.7
    container_name: test-mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"
      MYSQL_DATABASE: wordpress
    volumes:
      - /storage/docker/mysql-datadir:/var/lib/mysql
